const points=[
{id:'QC34-RS01',asset:'Quadro Compressores 3 e 4',component:'Relé térmico de sobrecarga',temp:75.6,ref:40,current:38.4,loss:31.8,cost:286.2,risk:94,p:'P20',action:'Inspecionar bornes e aplicar terminal prensado'},
{id:'QD-COMP-DJ01',asset:'QD — Compressores',component:'Disjuntor principal',temp:57.3,ref:40,current:31.2,loss:18.6,cost:167.4,risk:82,p:'P20',action:'Verificar oxidação e reapertar conexão'},
{id:'CF-CT02',asset:'Câmara Fria',component:'Contator de acionamento',temp:51.9,ref:40,current:27.8,loss:12.4,cost:111.6,risk:68,p:'P10',action:'Programar reaperto na próxima parada'},
{id:'QC34-CT03',asset:'Quadro Compressores 3 e 4',component:'Contator 03',temp:49.8,ref:40,current:25.1,loss:9.7,cost:87.3,risk:57,p:'P10',action:'Acompanhar e intervir em parada programada'},
{id:'QC34-CT04',asset:'Quadro Compressores 3 e 4',component:'Contator 04',temp:49.4,ref:40,current:24.9,loss:8.9,cost:80.1,risk:51,p:'P5',action:'Intensificar monitoramento térmico'},
{id:'CTF20-DJ01',asset:'CTF 20',component:'Disjuntor',temp:47.6,ref:40,current:22.3,loss:6.2,cost:55.8,risk:38,p:'P1',action:'Manter acompanhamento de rotina'}];
let currentFilter='Todos',selectedId=points[0].id,inspectionScheduled=false,toastTimer;
const $=id=>document.getElementById(id),br=n=>n.toFixed(1).replace('.',','),money=n=>n.toFixed(2).replace('.',',');
function renderFilters(){$('filters').innerHTML=['Todos','P20','P10','P5','P1'].map(f=>`<button class="${f===currentFilter?'on':''}" data-filter="${f}">${f}</button>`).join('')}
function renderRows(){const visible=currentFilter==='Todos'?points:points.filter(p=>p.p===currentFilter);$('rows').innerHTML=visible.map(p=>`<tr class="${p.id===selectedId?'selected':''}" data-id="${p.id}"><td><strong>${p.asset}</strong><small>${p.component} · ${p.id}</small></td><td><strong>${br(p.temp)}°C</strong><small>referência ${br(p.ref)}°C</small></td><td><strong>${br(p.current)} A</strong></td><td><strong>${br(p.loss)} kWh</strong><small>R$ ${money(p.cost)}/mês</small></td><td><div class="riskbar"><span><i style="width:${p.risk}%"></i></span><strong>${p.risk}%</strong></div></td><td><span class="tag ${p.p}">${p.p}</span></td></tr>`).join('')}
function selectPoint(id,scroll=true){const p=points.find(x=>x.id===id);if(!p)return;selectedId=id;$('assetTitle').textContent=p.asset;$('assetSub').textContent=`${p.component} · ${p.id}`;$('bigBadge').textContent=`${p.p} · ${p.p==='P20'?'Intervir agora':'Acompanhar'}`;$('tempValue').textContent=`${br(p.temp)}°`;$('limitLabel').textContent=`${br(p.ref)}°C`;$('deltaValue').textContent=`+${br(p.temp-p.ref)}°C`;$('currentValue').textContent=`${br(p.current)} A`;$('riskValue').textContent=`${p.risk}%`;$('lossValue').textContent=`${br(p.loss)} kWh`;$('costValue').textContent=`≈ R$ ${money(p.cost)}`;$('actionValue').textContent=p.action;$('tempGauge').style.setProperty('--gauge',p.risk);renderRows();if(scroll)document.querySelector('.critical-card').scrollIntoView({behavior:'smooth',block:'center'})}
function hideToast(){$('toast').classList.add('hidden');$('alertCount').textContent='2'}
function simulateAnomaly(){selectPoint(points[0].id,true);$('alertCount').textContent='3';$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(hideToast,6500)}
function toggleSchedule(){inspectionScheduled=!inspectionScheduled;const b=$('scheduleButton');b.classList.toggle('done',inspectionScheduled);b.querySelector('use').setAttribute('href',inspectionScheduled?'#i-check':'#i-clock');b.querySelector('span').textContent=inspectionScheduled?'Agendada':'Agendar'}
$('filters').addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;currentFilter=b.dataset.filter;renderFilters();renderRows()});
$('rows').addEventListener('click',e=>{const row=e.target.closest('tr[data-id]');if(row)selectPoint(row.dataset.id)});
$('simulateButton').addEventListener('click',simulateAnomaly);$('toastClose').addEventListener('click',hideToast);$('scheduleButton').addEventListener('click',toggleSchedule);$('menuButton').addEventListener('click',()=>$('sidebar').classList.toggle('open'));document.querySelectorAll('.sidebar a').forEach(a=>a.addEventListener('click',()=>$('sidebar').classList.remove('open')));
const sections=[...document.querySelectorAll('main section[id]')],navLinks=[...document.querySelectorAll('.nav-item,.mobile-nav a')];if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${visible.target.id}`))},{rootMargin:'-20% 0px -60% 0px',threshold:[0,.25,.6]});sections.forEach(s=>observer.observe(s))}
renderFilters();renderRows();selectPoint(selectedId,false);
